[package]
name = "sutrs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bootx64"
path = "src/boot.rs"


[dependencies]
elf = { version = "0.8.0", default-features = false }
log = "0.4.27"
uefi = { version = "0.35.0", features = ["panic_handler", "logger"] }
